spring:
  application:
    name: AccountService
  profiles.active: dev

server:
  port: 8080
  error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_param
      include-exception: false

app.jwt.secret: SECRET-KEY-VALUE

---
spring:
  sql.init.mode: always
  config.activate.on-profile: dev
  devtools.restart.enabled: true
  datasource:
    url: "jdbc:h2:mem:accounts_db"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9900

#debug: true
logging:
  path: /var/logs/
  file: /var/logs/accounts.log
  level:
    root: DEBUG


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:mysql://localhost:3306/accounts_db"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
  sql:
    init:
      mode: never  # No cargar datos iniciales en prod
  server:
    servlet.contextPath: /api/v1
    port: 9943
  logging:
    level:
      root: ERROR

---
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    default-produces-media-type: application/json
    default-consumes-media-type: application/json